FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.22 AS builder
ADD . /usr/src/network-resources-injector
RUN cd /usr/src/network-resources-injector && make

FROM registry.ci.openshift.org/ocp/4.22:base-rhel9-minimal
COPY --from=builder /usr/src/network-resources-injector/bin/webhook /usr/bin/
COPY --from=builder /usr/src/network-resources-injector/bin/installer /usr/bin/

LABEL io.k8s.display-name="SRIOV Admission Controller"
USER 1001
CMD ["webhook"]
