FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder

ADD . /usr/src/sriov-dp-admission-controller

WORKDIR /usr/src/sriov-dp-admission-controller

WORKDIR /

FROM registry.svc.ci.openshift.org/ocp/4.0:base

LABEL io.k8s.display-name="SRIOV Device Plugin Admission Controller"
