name: e2e
on: [pull_request]
jobs:
  e2e-test-cloud:
    name: E2E test cloud (GitHub VM)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.20', '1.21']
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Get tools, setup KinD cluster test environment
        run: source scripts/e2e_get_tools.sh && ./scripts/e2e_setup_cluster.sh

      - name: Execute E2E tests
        run: go test -timeout 60m ./test/e2e/...

# Disable for now because there is no dedicated server on which those tests can be run by GitHub.
  # e2e-test-self-hosted:
  #   name: E2E test self-hosted
  #   environment: nri-team
  #   runs-on: [self-hosted, Linux, hugepages]
  #   steps:
  #     - name: Set up Go version
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.13

  #     - name: Checkout code into the Go module directory
  #       uses: actions/checkout@v2

  #     - name: Get tools, setup KinD cluster test environment
  #       run: source scripts/e2e_get_tools.sh && ./scripts/e2e_setup_cluster.sh

  #     - name: Execute E2E tests
  #       run: go test -timeout 60m ./test/e2e/...

  #     - name: Tear down KinD cluster
  #       if: always()
  #       run: ./scripts/e2e_teardown_cluster.sh
